baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Chen Song'


Theme= 'archie'

copyright = "Â© Chen Song"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
	mode="auto"
	useCDN=false
	subtitle = "ğŸ‡ºğŸ‡¸ LMSW intern ä¸´åºŠå’¨è¯¢å¸ˆ, æ¥å—çº¿ä¸Šæ¥è®¿è€… TX, CO, VT, NJ, SC, FLï½œ ğŸ“® chensongtherapy@gmail.com"



[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"




[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4